# Generated by Django 4.0.6 on 2023-06-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Create_at', models.DateTimeField(auto_now=True)),
                ('Update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Enrollment', models.CharField(max_length=200, unique=True)),
                ('Create_at', models.DateTimeField(auto_now=True)),
                ('Update_at', models.DateTimeField()),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school')),
            ],
        ),
    ]
